name: demo_actions
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ['self-hosted','Linux','X64']
    steps:
      - name: change dir
        run: cd /var/www/html
      - uses: actions/checkout@v2
      - name: change ownership
        run: chown -R www-data:www-data /var/www/
